# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buson' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for buson
pod 'Alamofire-SwiftyJSON'
  target 'busonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'busonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
